import type { CartData } from "./types";

export const mockCartData: CartData = {
  items: [
    {
      id: "c-1",
      title: "Філе куряче охолоджене",
      brand: "Наша Ряба",
      weightVolume: "",
      countLabel: "2 кг",
      unitPrice: 94.9,
      total: 189.8,
    },
    {
      id: "c-2",
      title: "Йогурт грецький 10%",
      brand: "Галичина",
      weightVolume: "400 г",
      countLabel: "4 шт",
      unitPrice: 32.9,
      total: 131.6,
      oldTotal: 175.47,
      discountPercent: 25,
    },
    {
      id: "c-3",
      title: "Булгур",
      brand: "Жменька",
      weightVolume: "900 г",
      countLabel: "1 шт",
      unitPrice: 78.9,
      total: 78.9,
    },
    {
      id: "c-4",
      title: "Ягоди заморожені, мікс",
      brand: "Rud",
      weightVolume: "300 г",
      countLabel: "2 шт",
      unitPrice: 79.5,
      total: 159.0,
    },
    {
      id: "c-5",
      title: "Молоко мигдалеве",
      brand: "Alpro",
      weightVolume: "1 л",
      countLabel: "3 шт",
      unitPrice: 65.9,
      total: 197.7,
      oldTotal: 232.59,
      discountPercent: 15,
    },
  ],
  productsTotal: 1781.4,
  deliveryPrice: 69,
  totalPrice: 1850.4,
  discountSaved: 214.6,
  budgetLimit: 2000,
  deliveryTimeSlot: "18:00–20:00",
};