import type { MealItem, DailyMacroSummary } from "./types";

export const mockDailyMacros: DailyMacroSummary = {
  calories: { current: 1980, target: 1980 },
  protein: { current: 142, target: 145 },
  carbs: { current: 198, target: 205 },
  fat: { current: 54, target: 58 },
};

export const mockMealItems: MealItem[] = [
  {
    id: "m-1",
    time: "08:00",
    type: "СНІДАНОК",
    title: "Вівсянка на мигдалевому молоці з ягодами та чіа",
    cookingTimeMinutes: 10,
    calories: 520,
    protein: 18,
    fat: 12,
    carbs: 78,
    isCompleted: true,
    iconType: "bowl",
  },
  {
    id: "m-2",
    time: "13:00",
    type: "ОБІД",
    title: "Куряче філе з булгуром та печеними овочами",
    cookingTimeMinutes: 35,
    calories: 680,
    protein: 56,
    fat: 18,
    carbs: 62,
    isCompleted: true,
    iconType: "meat",
  },
  {
    id: "m-3",
    time: "16:30",
    type: "ПЕРЕКУС",
    note: "ПЕРЕД ТРЕНУВАННЯМ",
    title: "Грецький йогурт 10% з волоськими горіхами",
    cookingTimeMinutes: 0,
    calories: 240,
    protein: 22,
    fat: 11,
    carbs: 18,
    isCompleted: false,
    iconType: "milk",
  },
  {
    id: "m-4",
    time: "19:30",
    type: "ВЕЧЕРЯ",
    note: "ПІСЛЯ ТРЕНУВАННЯ",
    title: "Сирники з вишневим соусом без цукру",
    cookingTimeMinutes: 25,
    calories: 540,
    protein: 46,
    fat: 13,
    carbs: 40,
    isCompleted: false,
    iconType: "pancake",
  },
];